- name: reload fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: reloaded

- name: reload sshd
  service:
    name: sshd
    state: reloaded

- name: fix journal permissions
  ansible.builtin.shell: systemd-tmpfiles --create --prefix /var/log/journal
