- name: Install epel-release
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Install common packages
  ansible.builtin.package:
    name:
      - yum-utils
      - firewalld
      - fail2ban

- name: Install common packages
  ansible.builtin.package:
    name:
      - libselinux-python3
      - libsemanage-python3
      - python3-pip

- name: Start firewalld Service
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  ignore_errors: true

- name: Copy fail2ban config
  ansible.builtin.copy:
    src: jail.conf
    dest: /etc/fail2ban/jail.conf
  notify: reload fail2ban

- name: Copy sshd config
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  notify: reload sshd

- name: Create journal directory
  ansible.builtin.file:
    path: /var/log/journal
    state: directory
  notify: fix journal permissions

- name: Install NTP
  ansible.builtin.package:
    name: ntp
    state: present

- name: Start NTP
  ansible.builtin.service:
    name: ntpd
    state: started
    enabled: true
